# Generated by Django 5.0.1 on 2024-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_created_at', models.DateTimeField(auto_now_add=True)),
                ('instance_updated_at', models.DateTimeField(auto_now=True)),
                ('instance_is_active', models.BooleanField(default=True)),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
