version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: backend
    env_file:
      - env/.env
    volumes:
      - ../application:/sites/app/application
      - ../interface:/sites/app/interface
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: postgres
    env_file:
      - env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "50003:5432"


volumes:
  postgres_data:
